/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import view.Alteracao;
import java.sql.*;
import dao.ConnectionFactory;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author admin.elisson
 */
public class TELAPRINCIPAL extends javax.swing.JFrame {

    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * Creates new form TELAPRINCIPAL
     */
    public TELAPRINCIPAL() {
        initComponents();
        setSize(725, 690);
        setLocationRelativeTo(null);
        conexao = ConnectionFactory.conector();

    }

    private void pesquisar_cliente() {

        String sql = "select cpf as CPF,nome as NOME from tb_usuarios where cpf like?";
        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1, id_cpf.getText() + "%");
            rs = pst.executeQuery();
            tblusuarios.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void setar_campos() {
        int setar = tblusuarios.getSelectedRow();
        id_nome.setText(tblusuarios.getModel().getValueAt(setar, 1).toString());

    }

    //medo para cadastrar aluguel
    private void emitir_aluguel() {
        String sql = "insert into tb_aluguel(quant_alug, status,id_cpf,valor_alug) values (?,?,?,?)";
        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1, bquantidade.getSelectedItem().toString());
            pst.setString(2, bstatus.getText());
            pst.setString(3, id_nome.getText());
            pst.setString(4, bvalor.getText());
             int adicionado = pst.executeUpdate();
            System.out.println(adicionado);
            if (adicionado > 0) {
                JOptionPane.showMessageDialog(null, "Parabéns Aluguel Executado com sucesso foi Cadastrado com Sucesso!!!");
            }else{
                JOptionPane.showMessageDialog(null, "Erro no processo de Aluguel!!!");
           
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bstatus = new javax.swing.JCheckBox();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        bestoque = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        id_cpf = new javax.swing.JTextField();
        id_nome = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblusuarios = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        bvalor = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        bquantidade = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        bstatus.setText("SIM");
        getContentPane().add(bstatus);
        bstatus.setBounds(490, 480, 90, 23);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Aceito os termos de Serviço acima!");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(430, 450, 240, 15);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("NO MÁXIMO 4 BICICLETAS");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(60, 440, 240, 15);

        bestoque.setEditable(false);
        bestoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bestoqueActionPerformed(evt);
            }
        });
        getContentPane().add(bestoque);
        bestoque.setBounds(60, 340, 90, 20);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("ESTOQUE DE BICICLETAS");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(60, 320, 200, 17);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("VALOR CADA UMA SAI R$ 5,00!!!");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(60, 460, 240, 10);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("O ALUGUEL E FIXO DE 2 HORAS");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(60, 480, 240, 15);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("CPF");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(340, 100, 80, 14);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("NOME");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(550, 90, 70, 40);

        id_cpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_cpfActionPerformed(evt);
            }
        });
        id_cpf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                id_cpfKeyReleased(evt);
            }
        });
        getContentPane().add(id_cpf);
        id_cpf.setBounds(330, 120, 130, 20);

        id_nome.setEnabled(false);
        getContentPane().add(id_nome);
        id_nome.setBounds(470, 120, 220, 20);

        tblusuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "CPF", "NOME"
            }
        ));
        tblusuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblusuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblusuarios);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(330, 170, 360, 100);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images_Easy-Resize.com.jpg"))); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(50, 160, 230, 150);

        bvalor.setEditable(false);
        bvalor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(bvalor);
        bvalor.setBounds(440, 390, 200, 40);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("VALOR A PAGAR");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(440, 340, 220, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Nº DO PEDIDO");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(50, 100, 120, 17);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("DATA");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(190, 100, 90, 17);

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jTextField1);
        jTextField1.setBounds(50, 120, 110, 23);

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jTextField2);
        jTextField2.setBounds(190, 120, 110, 23);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("GoFun!");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(230, 10, 218, 44);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("VOLTAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(90, 520, 120, 31);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("AVANÇAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(500, 520, 130, 31);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("QUANTAS BIKES QUIERES");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 370, 200, 17);

        bquantidade.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bquantidade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4" }));
        bquantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bquantidadeActionPerformed(evt);
            }
        });
        getContentPane().add(bquantidade);
        bquantidade.setBounds(60, 400, 90, 30);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(266, 193, 0, 0);

        jLabel5.setBackground(new java.awt.Color(126, 217, 87));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/FUNDO_LOC.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, -10, 730, 620);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        emitir_aluguel();
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        TelaPrincipal01 tela = new TelaPrincipal01();
        tela.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bestoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bestoqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bestoqueActionPerformed

    private void id_cpfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_id_cpfKeyReleased

        // TODO add your handling code here:
    }//GEN-LAST:event_id_cpfKeyReleased

    private void id_cpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_cpfActionPerformed
        pesquisar_cliente();
        // TODO add your handling code here:
    }//GEN-LAST:event_id_cpfActionPerformed

    private void tblusuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblusuariosMouseClicked
        setar_campos();
        // TODO add your handling code here:
    }//GEN-LAST:event_tblusuariosMouseClicked

    private void bquantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bquantidadeActionPerformed
        double valor_fixo = 5.00;
        double resultado = 0;
        int num1 = 1;
        int num2 = 2;
        int num3 = 3;
        int num4 = 4;

        if (bquantidade.getSelectedItem().equals("1")) {
            resultado = num1 * valor_fixo;
        } else if (bquantidade.getSelectedItem().equals("2")) {
            resultado = num2 * valor_fixo;
        } else if (bquantidade.getSelectedItem().equals("3")) {
            resultado = num3 * valor_fixo;
        } else {
            resultado = num4 * valor_fixo;
        }
        
        bvalor.setText(String.valueOf(resultado));
        
        // TODO add your handling code here:
    }//GEN-LAST:event_bquantidadeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TELAPRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TELAPRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TELAPRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TELAPRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TELAPRINCIPAL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bestoque;
    private javax.swing.JComboBox bquantidade;
    private javax.swing.JCheckBox bstatus;
    private javax.swing.JTextField bvalor;
    private javax.swing.JTextField id_cpf;
    private javax.swing.JTextField id_nome;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTable tblusuarios;
    // End of variables declaration//GEN-END:variables
}
